image: node:10.11.0

options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm test
  branches:
    master:
      - step:
          caches:
            - node
          script:
          - export IMAGE_NAME=$DOCKER_HUB_USERNAME/$BITBUCKET_REPO_SLUG:latest
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
    staging:
      - step:
          caches:
            - node
          script:
          - export IMAGE_NAME=$DOCKER_HUB_USERNAME/$BITBUCKET_REPO_SLUG:staging
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
