export const SAVE_SPOTIFY_ACCESS_TOKEN: string = 'app/SAVE_SPOTIFY_ACCESS_TOKEN';
export const SEARCH_SPOTIFY_TRACK_SUCCESS: string = 'app/SEARCH_SPOTIFY_TRACK_SUCCESS';
export const SEARCH_SPOTIFY_TRACK_FAILURE: string = 'app/SEARCH_SPOTIFY_TRACK_FAILURE';
